# Regresión lineal simple en Python
## El paquete statsmodel para regresión lineal

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [8]:
import pandas as pd
import numpy as np

In [9]:
path_1 = "/content/drive/MyDrive/Machine Learning - Python/Datasets - Machine Learning/ads/Advertising.csv"

In [10]:
data_1 = pd.read_csv(path_1)

In [11]:
data_1.head()

,TV,Radio,Newspaper,Sales
0,230.1,37.8,69.2,22.1
1,44.5,39.3,45.1,10.4
2,17.2,45.9,69.3,9.3
3,151.5,41.3,58.5,18.5
4,180.8,10.8,58.4,12.9


In [6]:
import statsmodels.formula.api as smf
import numpy as pd

In [16]:
linear_model = smf.ols(formula = "Sales ~ TV", data = data_1).fit()

In [17]:
linear_model.params

Intercept    7.032594
TV           0.047537
dtype: float64

Hasta aquí, el modelo linear predictivo es `Sales = 7.032594 + 0.047537 * TV`

In [19]:
linear_model.pvalues

Intercept    1.406300e-35
TV           1.467390e-42
dtype: float64

In [20]:
linear_model.rsquared

0.611875050850071

In [21]:
linear_model.rsquared_adj

0.6099148238341623

In [22]:
linear_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.612
Model:                            OLS   Adj. R-squared:                  0.610
Method:                 Least Squares   F-statistic:                     312.1
Date:                Thu, 02 Nov 2023   Prob (F-statistic):           1.47e-42
Time:                        15:46:36   Log-Likelihood:                -519.05
No. Observations:                 200   AIC:                             1042.
Df Residuals:                     198   BIC:                             1049.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      7.0326      0.458     15.360      0.000       6.130       7.935
TV             0.0475      0.003     17.668      0.000       0.042       0.053
==============================================================================
Omnibus:                        0.531   Durbin-Watson:                   1.935
Prob(Omnibus):                  0.767   Jarque-Bera (JB):                0.669
Skew:                          -0.089   Prob(JB):                        0.716
Kurtosis:                       2.779   Cond. No.                         338.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [23]:
data_1["Sales_pred"] = 7.032594 + 0.047537 * data_1["TV"]

In [24]:
# RSE = error estándar residual

data_1["RSE"] = (data_1["Sales"] - data_1["Sales_pred"]) ** 2

In [25]:
# SSD = suma de los cuadrados de las diferencias

SSD = np.sum(data_1["RSE"])

In [26]:
# ahora, el cálculo de RSE mediante la fórmula

RSE = np.sqrt(SSD / (len(data_1) - 2))

In [27]:
RSE

3.2586563692380976

# Regresión Lineal Múltiple:

### Posibles modelos:

* Sales ~ TV
* Sales ~ Newspaper
* Sales ~ Radio
* Sales ~ TV + Newspaper
* Sales ~ TV + Radio
* Sales ~ Newspaper + Radio
* Sales ~ TV + Newspaper + Radio

In [28]:
# Añadir "Newspaper# al modelo existente

linear_model_2 = smf.ols(formula = "Sales ~ TV + Newspaper", data = data_1).fit()

In [29]:
linear_model_2.params

Intercept    5.774948
TV           0.046901
Newspaper    0.044219
dtype: float64

In [30]:
linear_model_2.pvalues

Intercept    3.145860e-22
TV           5.507584e-44
Newspaper    2.217084e-05
dtype: float64

In [31]:
linear_model_2.rsquared

0.6458354938293271

In [32]:
linear_model_2.rsquared_adj

0.6422399150864777

In [33]:
# Atentos al doble corchete; se está generando un subdataset, del data set original.

sales_pred_2 = linear_model_2.predict(data_1[["TV", "Newspaper"]])

In [34]:
sales_pred_2

0      19.626901
1       9.856348
2       9.646055
3      15.467318
4      16.837102
         ...    
195     8.176802
196    10.551220
197    14.359467
198    22.003458
199    17.045429
Length: 200, dtype: float64

In [35]:
SSD = np.sum((data_1["Sales"] - sales_pred_2) ** 2)

In [36]:
SSD

1918.5618118968277

In [37]:
RSE = np.sqrt(SSD / (len(data_1) - 2 - 1))

In [38]:
RSE

3.120719860252886

In [39]:
error = RSE / data_1['Sales'].mean()
error

0.22255089037282125

In [40]:
linear_model_2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.646
Model:                            OLS   Adj. R-squared:                  0.642
Method:                 Least Squares   F-statistic:                     179.6
Date:                Thu, 02 Nov 2023   Prob (F-statistic):           3.95e-45
Time:                        16:29:21   Log-Likelihood:                -509.89
No. Observations:                 200   AIC:                             1026.
Df Residuals:                     197   BIC:                             1036.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      5.7749      0.525     10.993      0.000       4.739       6.811
TV             0.0469      0.003     18.173      0.000       0.042       0.052
Newspaper      0.0442      0.010      4.346      0.000       0.024       0.064
==============================================================================
Omnibus:                        0.658   Durbin-Watson:                   1.969
Prob(Omnibus):                  0.720   Jarque-Bera (JB):                0.415
Skew:                          -0.093   Prob(JB):                        0.813
Kurtosis:                       3.122   Cond. No.                         410.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [41]:
# Añadir "Radio" al modelo existente con "TV"

linear_model_3 = smf.ols(formula = "Sales ~ TV + Radio", data = data_1).fit()

In [42]:
linear_model_3.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.897
Model:                            OLS   Adj. R-squared:                  0.896
Method:                 Least Squares   F-statistic:                     859.6
Date:                Thu, 02 Nov 2023   Prob (F-statistic):           4.83e-98
Time:                        16:30:04   Log-Likelihood:                -386.20
No. Observations:                 200   AIC:                             778.4
Df Residuals:                     197   BIC:                             788.3
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      2.9211      0.294      9.919      0.000       2.340       3.502
TV             0.0458      0.001     32.909      0.000       0.043       0.048
Radio          0.1880      0.008     23.382      0.000       0.172       0.204
==============================================================================
Omnibus:                       60.022   Durbin-Watson:                   2.081
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              148.679
Skew:                          -1.323   Prob(JB):                     5.19e-33
Kurtosis:                       6.292   Cond. No.                         425.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [43]:
sales_pred_3 = linear_model_3.predict(data_1[["TV", "Radio"]])
SSD = np.sum((data_1["Sales"] - sales_pred_3) ** 2)
RSE = np.sqrt(SSD / (len(data_1) - 2 - 1))

In [44]:
RSE

1.681360912508001

In [45]:
sales_mean = np.mean(data_1["Sales"])

In [46]:
# Veremos que este modelo no logra explicar aproximadamente el 11.9% de los datos
RSE / sales_mean

0.1199045043685506

In [48]:
linear_model_4 = smf.ols(formula = "Sales ~ TV + Radio + Newspaper", data = data_1).fit()

In [49]:
sales_pred_4 = linear_model_4.predict(data_1[["TV", "Radio", "Newspaper"]])
SSD = np.sum((data_1["Sales"] - sales_pred_4) ** 2)
RSE = np.sqrt(SSD / (len(data_1) - 3 - 1))

In [51]:
linear_model_4.params

Intercept    2.938889
TV           0.045765
Radio        0.188530
Newspaper   -0.001037
dtype: float64

In [50]:
linear_model_4.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.897
Model:                            OLS   Adj. R-squared:                  0.896
Method:                 Least Squares   F-statistic:                     570.3
Date:                Thu, 02 Nov 2023   Prob (F-statistic):           1.58e-96
Time:                        16:31:30   Log-Likelihood:                -386.18
No. Observations:                 200   AIC:                             780.4
Df Residuals:                     196   BIC:                             793.6
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      2.9389      0.312      9.422      0.000       2.324       3.554
TV             0.0458      0.001     32.809      0.000       0.043       0.049
Radio          0.1885      0.009     21.893      0.000       0.172       0.206
Newspaper     -0.0010      0.006     -0.177      0.860      -0.013       0.011
==============================================================================
Omnibus:                       60.414   Durbin-Watson:                   2.084
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              151.241
Skew:                          -1.327   Prob(JB):                     1.44e-33
Kurtosis:                       6.332   Cond. No.                         454.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

# Multicolinealidad

### Factor Inflación de la Varianza

* VIF = 1: Las variables no están correlacionadas.
* VIF < 5: Las variables tienen una correlación moderada y pueden seguir en el modelo.
* VIF >= 5: Las variables están altamente correlacionadas y deben desaparecer del modelo.

In [52]:
# Newspaper ~ TV + Radio --> R^2 VIF = 1 / (1 - R^2)

lm_newspaper = smf.ols(formula = "Newspaper ~ TV + Radio", data = data_1).fit()
rsquared_newspaper = lm_newspaper.rsquared
VIF_1 = 1 / (1 - rsquared_newspaper)
VIF_1

1.1451873787239288

In [53]:
# TV ~ Newspaper + Radio --> R^2 VIF = 1 / (1 - R^2)

lm_TV = smf.ols(formula = "TV ~ Newspaper + Radio", data = data_1).fit()
rsquared_TV = lm_TV.rsquared
VIF_2 = 1 / (1 - rsquared_TV)
VIF_2

1.00461078493965

In [54]:
# Radio ~ TV + Newspaper --> R^2 VIF = 1 / (1 - R^2)

lm_radio = smf.ols(formula = "Radio ~ TV + Newspaper", data = data_1).fit()
rsquared_radio = lm_radio.rsquared
VIF_3 = 1 / (1 - rsquared_radio)
VIF_3

1.1449519171055353

# Conclusión, no existe alto grado de colinealidad entre las tres variables. Por lo tanto, el modelo de Sales a partir de las tres variables en cuestión, resulta apto.
